"use client";

import { Check, Clock3, CreditCard, LoaderCircle, MessageCircle, PackageCheck, QrCode, ShieldCheck, Store, Tag, Truck, XCircle } from "lucide-react";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { money } from "@/lib/products";
import { storeConfig, whatsappUrl } from "@/lib/store-config";
import { getSupabase } from "@/lib/supabase";
import { useStore } from "./store-provider";
import { analyticsItem, trackItems } from "@/lib/analytics";

type ShippingMethod={id:string;name:string;code:string;method_type:"flat_rate"|"pickup";flat_rate:number;free_shipping_threshold:number|null;estimated_min_days:number;estimated_max_days:number;shipping_zones:{name:string;code:string}|{name:string;code:string}[]|null};
type Quote={subtotal:number;discount:number;shipping_fee:number;total:number;coupon_code:string|null;shipping_method_id:string;shipping_method:string;estimated_min_days:number;estimated_max_days:number};
type QPayState={orderNumber:string;qrImage:string|null;shortUrl:string|null;urls:{name?:string;description?:string;logo?:string;link?:string}[];total:number};
const zoneName=(method:ShippingMethod)=>{const zone=Array.isArray(method.shipping_zones)?method.shipping_zones[0]:method.shipping_zones;return zone?.name||"Хүргэлт"};

export default function CheckoutForm({compact=false}:{compact?:boolean}){
  const {cart,clear}=useStore();
  const [orderId,setOrderId]=useState(""),[submitting,setSubmitting]=useState(false),[error,setError]=useState("");
  const [methods,setMethods]=useState<ShippingMethod[]>([]),[methodsLoading,setMethodsLoading]=useState(true),[selectedMethod,setSelectedMethod]=useState("");
  const [quote,setQuote]=useState<Quote|null>(null),[quoteLoading,setQuoteLoading]=useState(false),[couponInput,setCouponInput]=useState(""),[appliedCoupon,setAppliedCoupon]=useState(""),[couponMessage,setCouponMessage]=useState("");
  const [paymentMethod,setPaymentMethod]=useState<"bank_transfer"|"qpay">("qpay"),[qpay,setQpay]=useState<QPayState|null>(null),[paymentStatus,setPaymentStatus]=useState<"pending"|"paid"|"failed"|"cancelled">("pending");
  const [form,setForm]=useState({name:"",phone:"",email:"",address:"",notes:"",website:""});
  const chosen=methods.find(method=>method.id===selectedMethod),fallbackSubtotal=cart.reduce((sum,item)=>sum+item.price*item.qty,0);
  const items=useMemo(()=>cart.map(item=>({id:item.id,qty:item.qty})),[cart]);
  const checkoutTracked=useRef(false);
  const checkoutItems=useRef(cart.map(item=>analyticsItem(item,item.qty)));
  useEffect(()=>{if(cart.length)checkoutItems.current=cart.map(item=>analyticsItem(item,item.qty))},[cart]);
  useEffect(()=>{const track=()=>{if(!checkoutTracked.current&&cart.length&&window.tomocAnalyticsConsent){checkoutTracked.current=true;trackItems("begin_checkout",cart.map(item=>analyticsItem(item,item.qty)),{},{dedupeKey:"begin_checkout:current",dedupeMs:1000})}};track();window.addEventListener("tomoc:analytics-ready",track);return()=>window.removeEventListener("tomoc:analytics-ready",track)},[cart]);
  const update=(field:keyof typeof form,value:string)=>setForm(current=>({...current,[field]:value}));
  useEffect(()=>{let active=true;fetch("/api/checkout/quote").then(async response=>{const result=await response.json();if(!response.ok)throw new Error(result.error||"Хүргэлтийн сонголт ачаалж чадсангүй.");if(active){setMethods(result.methods||[]);setSelectedMethod(result.methods?.[0]?.id||"")}}).catch(cause=>active&&setError(cause instanceof Error?cause.message:"Алдаа гарлаа.")).finally(()=>active&&setMethodsLoading(false));return()=>{active=false}},[]);
  const requestQuote=useCallback(async(coupon:string,showCouponResult=false)=>{if(!selectedMethod||!items.length)return;setQuoteLoading(true);if(showCouponResult)setCouponMessage("");try{const response=await fetch("/api/checkout/quote",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({items,couponCode:coupon,shippingMethodId:selectedMethod,phone:form.phone})});const result=await response.json();if(!response.ok)throw new Error(result.error||"Тооцоолол хийж чадсангүй.");setQuote(result.quote);if(showCouponResult){setAppliedCoupon(result.quote.coupon_code||"");setCouponMessage(result.quote.coupon_code?`${result.quote.coupon_code} купон амжилттай хэрэгжлээ.`:"")}}catch(cause){if(showCouponResult){setAppliedCoupon("");setCouponMessage(cause instanceof Error?cause.message:"Купон шалгаж чадсангүй.")}else setError(cause instanceof Error?cause.message:"Тооцооллын алдаа гарлаа.")}finally{setQuoteLoading(false)}},[selectedMethod,items,form.phone]);
  useEffect(()=>{if(!selectedMethod||!items.length)return;const timer=window.setTimeout(()=>void requestQuote(appliedCoupon),250);return()=>window.clearTimeout(timer)},[selectedMethod,items,appliedCoupon,requestQuote]);
  const applyCoupon=()=>{const code=couponInput.trim().toUpperCase();if(!code){setAppliedCoupon("");setCouponMessage("");void requestQuote("");return}void requestQuote(code,true)};
  useEffect(()=>{if(chosen&&cart.length)trackItems("add_shipping_info",cart.map(item=>analyticsItem(item,item.qty)),{shipping_tier:chosen.name},{dedupeKey:`add_shipping_info:${chosen.id}`,dedupeMs:1500})},[chosen,cart]);
  useEffect(()=>{if(cart.length)trackItems("add_payment_info",cart.map(item=>analyticsItem(item,item.qty)),{payment_type:paymentMethod},{dedupeKey:`add_payment_info:${paymentMethod}`,dedupeMs:1500})},[paymentMethod,cart]);
  useEffect(()=>{if(!qpay||paymentStatus!=="pending")return;let active=true;const check=async()=>{try{const response=await fetch("/api/qpay/status",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({orderNumber:qpay.orderNumber,phone:form.phone})});const result=await response.json();if(active&&response.ok&&result.status){setPaymentStatus(result.status);if(result.status==="paid"){trackItems("purchase",checkoutItems.current,{transaction_id:qpay.orderNumber,value:qpay.total,currency:"MNT"},{dedupeKey:`purchase:${qpay.orderNumber}`,oncePerSession:true});setOrderId(qpay.orderNumber);setQpay(null)}}}catch{}};void check();const timer=window.setInterval(check,5000);return()=>{active=false;window.clearInterval(timer)}},[qpay,paymentStatus,form.phone]);
  const cancelPayment=async()=>{if(!qpay)return;setSubmitting(true);try{const response=await fetch("/api/qpay/cancel",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({orderNumber:qpay.orderNumber,phone:form.phone})});const result=await response.json();if(!response.ok)throw new Error(result.error||"Цуцалж чадсангүй.");setPaymentStatus("cancelled")}catch(cause){setError(cause instanceof Error?cause.message:"Алдаа гарлаа.")}finally{setSubmitting(false)}};
  const submit=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!cart.length||submitting||!chosen)return;setSubmitting(true);setError("");const popup=paymentMethod==="bank_transfer"?window.open("","_blank"):null;try{const session=(await getSupabase()?.auth.getSession())?.data.session;const response=await fetch("/api/orders",{method:"POST",headers:{"content-type":"application/json",...(session?{authorization:`Bearer ${session.access_token}`}:{})},body:JSON.stringify({customerName:form.name,phone:form.phone,email:form.email,location:zoneName(chosen),address:chosen.method_type==="pickup"?"TOMOC Store-оос өөрөө авах":form.address,notes:form.notes,website:form.website,items,couponCode:appliedCoupon,shippingMethodId:selectedMethod,paymentMethod})});const result=await response.json();if(!response.ok)throw new Error(result.error||"Захиалга үүсгэж чадсангүй.");const id=result.orderNumber;if(!id)throw new Error("Захиалгын дугаар үүссэнгүй.");const total=result.quote?.total??quote?.total??fallbackSubtotal;if(paymentMethod==="qpay"&&result.qpay){setPaymentStatus("pending");setQpay({orderNumber:id,qrImage:result.qpay.qrImage,shortUrl:result.qpay.shortUrl,urls:result.qpay.urls||[],total});clear();return}const itemLines=cart.map(item=>`• ${item.name} × ${item.qty} — ${money(item.price*item.qty)}`).join("\n");const message=["Сайн байна уу! TOMOC Store-д захиалга өгч байна.",`Захиалгын дугаар: ${id}`,"",itemLines,"",appliedCoupon?`Купон: ${appliedCoupon}`:"",`Хүргэлт: ${result.quote?.shippingMethod||chosen.name}`,`Нийт: ${money(total)}`,`Нэр: ${form.name}`,`Утас: ${form.phone}`,`Байршил: ${zoneName(chosen)}`,chosen.method_type!=="pickup"?`Хаяг: ${form.address}`:"",form.notes?`Тайлбар: ${form.notes}`:""].filter(Boolean).join("\n");const destination=`${whatsappUrl}?text=${encodeURIComponent(message)}`;if(popup)popup.location.href=destination;else window.location.href=destination;setOrderId(id);clear()}catch(cause){if(popup)popup.close();setError(cause instanceof Error?cause.message:"Сүлжээний алдаа гарлаа.")}finally{setSubmitting(false)}};
  if(qpay)return <div className="grid min-h-[560px] place-items-center text-center"><div className="w-full max-w-sm"><div className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-cloud dark:bg-neutral-800"><QrCode size={30}/></div><p className="eyebrow mt-5">QPAY SECURE PAYMENT</p><h2 className="display-serif mt-2 text-4xl">{paymentStatus==="pending"?"QR кодоо уншуулна уу":paymentStatus==="cancelled"?"Төлбөр цуцлагдлаа":"Төлбөр амжилтгүй"}</h2><p className="mt-3 text-sm text-neutral-500">{qpay.orderNumber} • {money(qpay.total)}</p>{paymentStatus==="pending"&&<>{qpay.qrImage?<img src={qpay.qrImage} alt="QPay төлбөрийн QR код" width="260" height="260" className="mx-auto mt-6 rounded-3xl bg-white p-3 shadow-soft"/>:<div className="mx-auto mt-6 grid h-[260px] w-[260px] place-items-center rounded-3xl bg-cloud text-sm text-neutral-500">QR зураг ирсэнгүй</div>}<div className="mt-4 grid gap-2">{qpay.shortUrl&&<a href={qpay.shortUrl} target="_blank" rel="noreferrer" className="btn btn-black w-full">QPay-аар нээх</a>}{qpay.urls.slice(0,4).map((item,index)=>item.link?<a key={`${item.name}-${index}`} href={item.link} className="btn w-full bg-cloud text-sm dark:bg-neutral-800">{item.description||item.name||"Банкны апп нээх"}</a>:null)}</div><p role="status" className="mt-5 flex items-center justify-center gap-2 text-sm text-neutral-500"><LoaderCircle className="animate-spin" size={16}/> Төлбөрийн төлөв шалгаж байна...</p><button disabled={submitting} onClick={cancelPayment} className="mt-4 text-sm font-bold text-red-600 underline underline-offset-4">Төлбөр цуцлах</button></>}{paymentStatus!=="pending"&&<a href="/#products" className="btn btn-black mt-7">Дэлгүүр рүү буцах</a>}{error&&<p role="alert" className="mt-4 rounded-xl bg-amber-50 p-3 text-sm text-amber-800">{error}</p>}</div></div>;
  if(orderId)return <div className="grid min-h-[430px] place-items-center text-center"><div><div className="mx-auto grid h-20 w-20 place-items-center rounded-full bg-green-50 text-green-700"><PackageCheck size={42}/></div><p className="eyebrow mt-6">{paymentMethod==="qpay"?"ТӨЛБӨР АМЖИЛТТАЙ":"ЗАХИАЛГА ҮҮСЛЭЭ"}</p><h2 className="mt-2 text-2xl font-bold">{orderId}</h2><p className="mx-auto mt-4 max-w-sm text-sm leading-6 text-neutral-500">{paymentMethod==="qpay"?"QPay төлбөр баталгаажиж, захиалга боловсруулах шатанд орлоо.":"Захиалга системд хадгалагдлаа. WhatsApp дахь бэлэн мессежийг илгээж баталгаажуулна уу."}</p>{paymentMethod!=="qpay"&&<a href={`${whatsappUrl}?text=${encodeURIComponent(`Сайн байна уу! ${orderId} дугаартай захиалгаа баталгаажуулна уу.`)}`} target="_blank" rel="noreferrer" className="btn mt-6 bg-[#25D366] text-white"><MessageCircle size={18}/> WhatsApp дахин нээх</a>}</div></div>;
  if(!cart.length)return <div className="grid min-h-[360px] place-items-center text-center"><div><PackageCheck className="mx-auto text-neutral-400" size={42}/><h2 className="mt-4 text-xl font-bold">Сагс хоосон байна</h2><p className="mt-2 text-sm text-neutral-500">Бүтээгдэхүүн сонгоод захиалгаа үргэлжлүүлнэ үү.</p><a href="/#products" className="btn btn-black mt-5">Бүтээгдэхүүн үзэх</a></div></div>;
  return <form onSubmit={submit} className="space-y-4">
    {!compact&&<div className="mb-6"><p className="eyebrow">SECURE CHECKOUT</p><h1 className="display-serif mt-2 text-5xl">Захиалгаа баталгаажуулах</h1><p className="mt-3 text-sm text-neutral-500">Купон, хүргэлт, төлбөрийн сонголтоо нэг дор баталгаажуулна.</p></div>}
    <input className="hidden" tabIndex={-1} autoComplete="off" aria-hidden="true" name="website" value={form.website} onChange={event=>update("website",event.target.value)}/>
    <div className="grid grid-cols-2 gap-2"><a href={`tel:${storeConfig.contact.orderPhone}`} className="rounded-2xl bg-ink p-4 text-white"><span className="block text-[10px] font-bold uppercase tracking-wider text-white/55">Захиалгын утас</span><b className="mt-1 block text-lg">{storeConfig.contact.orderPhone}</b></a><a href={whatsappUrl} target="_blank" rel="noreferrer" className="rounded-2xl bg-[#25D366] p-4 text-white"><span className="block text-[10px] font-bold uppercase tracking-wider text-white/70">WhatsApp</span><b className="mt-1 block text-lg">{storeConfig.contact.whatsappDisplay}</b></a></div>
    <div className="grid grid-cols-2 gap-3"><input required className="input" aria-label="Захиалагчийн нэр" placeholder="Нэр" value={form.name} onChange={event=>update("name",event.target.value)}/><input required className="input" aria-label="Утасны дугаар" placeholder="Утас" inputMode="tel" value={form.phone} onChange={event=>update("phone",event.target.value)}/></div>
    <input type="email" className="input" aria-label="И-мэйл хаяг" placeholder="И-мэйл (заавал биш)" value={form.email} onChange={event=>update("email",event.target.value)}/>
    <fieldset className="card p-5"><legend className="px-2 text-sm font-bold">Хүргэлтийн арга</legend>{methodsLoading?<div className="flex items-center gap-2 py-5 text-sm text-neutral-500"><LoaderCircle size={17} className="animate-spin"/> Ачаалж байна...</div>:methods.length?<div className="space-y-2">{methods.map(method=><label key={method.id} className={`flex cursor-pointer items-start gap-3 rounded-2xl border p-4 ${selectedMethod===method.id?"border-gold bg-white dark:bg-neutral-800":"border-transparent bg-[var(--card)]"}`}><input type="radio" name="shipping" className="mt-1" checked={selectedMethod===method.id} onChange={()=>setSelectedMethod(method.id)}/>{method.method_type==="pickup"?<Store size={19}/>:<Truck size={19}/>}<span className="min-w-0 flex-1"><b className="block text-sm">{method.name}</b><span className="mt-1 block text-xs text-neutral-500">{zoneName(method)} • {method.estimated_max_days===0?"Өнөөдөр":`${method.estimated_min_days}–${method.estimated_max_days} өдөр`}</span></span><b className="text-sm">{method.method_type==="pickup"?"Үнэгүй":method.free_shipping_threshold?`${money(method.flat_rate)}*`:money(method.flat_rate)}</b></label>)}</div>:<p className="py-5 text-sm text-neutral-500">Хүргэлтийн сонголт алга.</p>}</fieldset>
    {chosen?.method_type!=="pickup"&&<input required className="input" aria-label="Хүргэлтийн хаяг" placeholder="Хүргэлтийн дэлгэрэнгүй хаяг" value={form.address} onChange={event=>update("address",event.target.value)}/>}<textarea className="input h-24 py-3" aria-label="Нэмэлт тайлбар" placeholder="Нэмэлт тайлбар (хороо, орц, тоот)" value={form.notes} onChange={event=>update("notes",event.target.value)}/>
    <div className="card p-5"><label className="flex items-center gap-2 text-sm font-bold" htmlFor="coupon"><Tag size={17}/> Купоны код</label><div className="mt-3 grid grid-cols-[1fr_auto] gap-2"><input id="coupon" className="input uppercase" placeholder="Жишээ: TOMOC10" value={couponInput} onChange={event=>setCouponInput(event.target.value.toUpperCase())}/><button type="button" onClick={applyCoupon} disabled={quoteLoading} className="btn btn-black h-[50px] disabled:opacity-50">{quoteLoading?<LoaderCircle className="animate-spin" size={17}/>:appliedCoupon?<Check size={17}/>:null}{appliedCoupon?"Хэрэгжсэн":"Шалгах"}</button></div>{couponMessage&&<p role="status" className={`mt-3 text-xs ${appliedCoupon?"text-green-700":"text-amber-700"}`}>{couponMessage}</p>}</div>
    <div className="card space-y-3 p-5 text-sm">{cart.map(item=><div key={item.id} className="flex justify-between gap-4"><span>{item.name} × {item.qty}</span><b>{money(item.price*item.qty)}</b></div>)}<div className="space-y-2 border-t border-black/10 pt-3 dark:border-white/10"><div className="flex justify-between text-neutral-500"><span>Дэд дүн</span><span>{money(quote?.subtotal??fallbackSubtotal)}</span></div>{Boolean(quote?.discount)&&<div className="flex justify-between text-green-700"><span>Хөнгөлөлт</span><span>−{money(quote!.discount)}</span></div>}<div className="flex justify-between text-neutral-500"><span>Хүргэлт</span><span>{quote?.shipping_fee===0?"Үнэгүй":quote?money(quote.shipping_fee):"—"}</span></div><div className="flex justify-between pt-2 text-lg font-bold"><span>Нийт</span><span>{quoteLoading?"…":money(quote?.total??fallbackSubtotal)}</span></div></div>{quote&&<p className="flex items-center gap-2 text-xs text-neutral-500"><Clock3 size={14}/> Тооцоолсон хүргэлт: {quote.estimated_max_days===0?"өнөөдөр":`${quote.estimated_min_days}–${quote.estimated_max_days} өдөр`}</p>}</div>
    <fieldset className="card p-5"><legend className="px-2 text-sm font-bold">Төлбөрийн арга</legend><div className="grid gap-2 sm:grid-cols-2"><label className={`flex cursor-pointer items-start gap-3 rounded-2xl border p-4 ${paymentMethod==="qpay"?"border-gold":"border-[var(--line)]"}`}><input type="radio" name="payment" className="mt-1" checked={paymentMethod==="qpay"} onChange={()=>setPaymentMethod("qpay")}/><QrCode size={20}/><span><b className="block text-sm">QPay</b><span className="mt-1 block text-xs text-neutral-500">QR болон банкны апп</span></span></label><label className={`flex cursor-pointer items-start gap-3 rounded-2xl border p-4 ${paymentMethod==="bank_transfer"?"border-gold":"border-[var(--line)]"}`}><input type="radio" name="payment" className="mt-1" checked={paymentMethod==="bank_transfer"} onChange={()=>setPaymentMethod("bank_transfer")}/><CreditCard size={20}/><span><b className="block text-sm">{storeConfig.payment.method}</b><span className="mt-1 block text-xs text-neutral-500">{storeConfig.payment.instructions}</span></span></label></div><p className="mt-4 flex items-center gap-2 text-xs text-neutral-500"><ShieldCheck size={15}/> Төлбөрийн мэдээлэл хамгаалагдсан server connection-оор дамжина.</p></fieldset>
    {error&&<p role="alert" className="rounded-xl bg-amber-50 p-3 text-sm text-amber-800">{error}</p>}
    <button disabled={submitting||quoteLoading||!selectedMethod} className={`btn w-full text-white disabled:opacity-50 ${paymentMethod==="qpay"?"bg-ink":"bg-[#25D366]"}`}>{submitting?<LoaderCircle className="animate-spin" size={18}/>:paymentMethod==="qpay"?<QrCode size={18}/>:<MessageCircle size={18}/>} {submitting?"Захиалга үүсгэж байна...":paymentMethod==="qpay"?"QPay-аар төлөх":"WhatsApp-аар захиалга илгээх"}</button><p className="text-center text-[11px] leading-5 text-neutral-500">Үнэ, купон, үлдэгдэл болон хүргэлтийн төлбөр сервер дээр transaction дотор дахин шалгагдана.</p>
  </form>;
}
