"use client";

import { BadgeCheck, LoaderCircle, Star } from "lucide-react";
import { useEffect, useState } from "react";
import { getSupabase } from "@/lib/supabase";

type Review={id:string;customer_name:string;rating:number;title:string|null;body:string;is_verified:boolean;created_at:string};
type Summary={average:number;total:number;distribution:Record<number,number>};
const emptySummary:Summary={average:0,total:0,distribution:{1:0,2:0,3:0,4:0,5:0}};

export default function ProductReviews({slug}:{slug:string}){
  const [reviews,setReviews]=useState<Review[]>([]),[summary,setSummary]=useState<Summary>(emptySummary);
  const [loading,setLoading]=useState(true),[loadError,setLoadError]=useState("");
  const [rating,setRating]=useState(5),[submitting,setSubmitting]=useState(false),[message,setMessage]=useState(""),[form,setForm]=useState({customerName:"",orderNumber:"",phone:"",title:"",body:""});
  useEffect(()=>{let active=true;fetch(`/api/reviews?product=${encodeURIComponent(slug)}`).then(async response=>{const result=await response.json();if(!response.ok)throw new Error(result.error||"Сэтгэгдэл ачаалж чадсангүй.");if(active){setReviews(result.reviews||[]);setSummary(result.summary||emptySummary)}}).catch(error=>active&&setLoadError(error.message)).finally(()=>active&&setLoading(false));return()=>{active=false}},[slug]);
  const submit=async(event:React.FormEvent)=>{event.preventDefault();if(submitting)return;setSubmitting(true);setMessage("");try{const session=(await getSupabase()?.auth.getSession())?.data.session;const response=await fetch("/api/reviews",{method:"POST",headers:{"content-type":"application/json",...(session?{authorization:`Bearer ${session.access_token}`}:{})},body:JSON.stringify({...form,rating,product:slug})});const result=await response.json();if(!response.ok)throw new Error(result.error||"Сэтгэгдэл илгээж чадсангүй.");setMessage(result.message);setForm({customerName:"",orderNumber:"",phone:"",title:"",body:""});setRating(5)}catch(error){setMessage(error instanceof Error?error.message:"Алдаа гарлаа.")}finally{setSubmitting(false)}};
  return <section className="section border-t border-black/[.06] dark:border-white/10" aria-labelledby="reviews-title"><div className="container">
    <div className="grid gap-10 lg:grid-cols-[.75fr_1.25fr]">
      <div><span className="eyebrow">БАТАЛГААЖСАН СЭТГЭГДЭЛ</span><h2 id="reviews-title" className="display-serif mt-3 text-4xl md:text-5xl">Хэрэглэгчдийн үнэлгээ</h2>
        {loading?<div className="mt-8 flex items-center gap-2 text-sm text-neutral-500"><LoaderCircle className="animate-spin" size={18}/> Уншиж байна...</div>:loadError?<p role="alert" className="mt-8 rounded-2xl bg-amber-50 p-4 text-sm text-amber-800">{loadError}</p>:<><div className="mt-8 flex items-end gap-3"><b className="display-serif text-6xl">{summary.average||"—"}</b><div className="pb-2"><Stars value={Math.round(summary.average)}/><p className="mt-1 text-xs text-neutral-500">{summary.total} сэтгэгдэл</p></div></div><div className="mt-7 space-y-2">{[5,4,3,2,1].map(star=><div key={star} className="grid grid-cols-[32px_1fr_28px] items-center gap-3 text-xs"><span>{star}★</span><div className="h-1.5 overflow-hidden rounded-full bg-cloud dark:bg-neutral-800"><div className="h-full rounded-full bg-[#b79762]" style={{width:`${summary.total?(summary.distribution[star]||0)/summary.total*100:0}%`}}/></div><span className="text-right text-neutral-500">{summary.distribution[star]||0}</span></div>)}</div></>}
      </div>
      <div>{!loading&&!loadError&&(reviews.length?<div className="space-y-4">{reviews.map(review=><article key={review.id} className="rounded-[26px] border border-black/[.07] p-6 dark:border-white/10"><div className="flex flex-wrap items-center justify-between gap-3"><Stars value={review.rating}/><time className="text-xs text-neutral-400">{new Intl.DateTimeFormat("mn-MN",{dateStyle:"medium"}).format(new Date(review.created_at))}</time></div>{review.title&&<h3 className="mt-4 font-bold">{review.title}</h3>}<p className="mt-3 leading-7 text-neutral-600 dark:text-neutral-300">{review.body}</p><div className="mt-5 flex items-center gap-2 text-sm font-bold">{review.customer_name}{review.is_verified&&<span className="inline-flex items-center gap-1 rounded-full bg-green-50 px-2.5 py-1 text-[11px] text-green-700"><BadgeCheck size={14}/> Худалдан авалт баталгаажсан</span>}</div></article>)}</div>:<div className="rounded-[26px] bg-cloud p-8 text-center dark:bg-neutral-900"><Star className="mx-auto text-gold"/><h3 className="mt-4 font-bold">Анхны сэтгэгдлийг үлдээгээрэй</h3><p className="mt-2 text-sm text-neutral-500">Баталгаажсан захиалгатай хэрэглэгч сэтгэгдэл бичих боломжтой.</p></div>)}
        <details className="mt-6 rounded-[26px] bg-cloud p-6 dark:bg-neutral-900"><summary className="cursor-pointer font-bold">Сэтгэгдэл бичих</summary><form onSubmit={submit} className="mt-6 space-y-3"><fieldset><legend className="mb-2 text-xs font-bold">Үнэлгээ</legend><div className="flex gap-1">{[1,2,3,4,5].map(star=><button type="button" key={star} onClick={()=>setRating(star)} aria-label={`${star} од`} aria-pressed={rating===star} className="p-1 text-gold"><Star fill={star<=rating?"currentColor":"none"}/></button>)}</div></fieldset><div className="grid gap-3 sm:grid-cols-2"><input required className="input" placeholder="Таны нэр" value={form.customerName} onChange={e=>setForm({...form,customerName:e.target.value})}/><input required className="input" placeholder="Захиалгын дугаар" value={form.orderNumber} onChange={e=>setForm({...form,orderNumber:e.target.value.toUpperCase()})}/></div><input required className="input" inputMode="tel" placeholder="Захиалгын утас" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><input className="input" placeholder="Гарчиг (заавал биш)" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><textarea required minLength={10} maxLength={1500} className="input h-32 py-3" placeholder="Туршлагаа хуваалцаарай..." value={form.body} onChange={e=>setForm({...form,body:e.target.value})}/>{message&&<p role="status" className="rounded-xl bg-white p-3 text-sm dark:bg-neutral-800">{message}</p>}<button disabled={submitting} className="btn btn-black w-full disabled:opacity-50">{submitting?"Илгээж байна...":"Сэтгэгдэл илгээх"}</button><p className="text-[11px] leading-5 text-neutral-500">Захиалгын дугаар, утсыг зөвхөн худалдан авалтыг баталгаажуулахад ашиглана. Нийтэд харуулахгүй.</p></form></details>
      </div>
    </div>
  </div></section>
}

function Stars({value}:{value:number}){return <span className="flex text-[#b79762]" aria-label={`${value} одны үнэлгээ`}>{[1,2,3,4,5].map(star=><Star key={star} size={16} fill={star<=value?"currentColor":"none"}/>)}</span>}
