"use client";
import Image from "next/image";
import Link from "next/link";
import dynamic from "next/dynamic";
import { AnimatePresence, motion } from "framer-motion";
import { ArrowRight, Bot, Check, ChevronDown, ChevronLeft, ChevronRight, CircleUserRound, Clock3, Facebook, Heart, Instagram, LoaderCircle, Menu, MessageCircle, Minus, Moon, PackageCheck, Plus, Search, ShieldCheck, ShoppingBag, Sparkles, Star, Sun, Truck, X, Zap } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import { money, type Product } from "@/lib/products";
import { storeConfig, whatsappUrl } from "@/lib/store-config";
import { useStore } from "./store-provider";
import { MobileBuyBar } from "./luxury-sections";
import CheckoutForm from "./checkout-form";
import WishlistLink from "./wishlist-link";
import { analyticsItem, trackEvent, trackItems } from "@/lib/analytics";
import { defaultSiteContent, type SiteContent } from "@/lib/site-content";
import type { ChatContext } from "@/lib/assistant/types";

const CustomerAccount=dynamic(()=>import("./customer-account"),{loading:()=> <div className="grid min-h-[320px] place-items-center"><LoaderCircle className="animate-spin"/></div>});

type Modal = "cart"|"account"|"track"|"checkout"|"search"|"product"|null;
const fade={initial:{opacity:0,y:20},whileInView:{opacity:1,y:0},viewport:{once:true,margin:"-80px"},transition:{duration:.55}};
const messenger=storeConfig.contact.messengerUrl;
const whatsapp=whatsappUrl;
const facebook=storeConfig.contact.facebookUrl;

export default function Storefront(){
  const {cartCount,add}=useStore(); const [modal,setModal]=useState<Modal>(null); const [selected,setSelected]=useState<Product|null>(null); const [catalog,setCatalog]=useState<Product[]>([]); const [dark,setDark]=useState(false); const [menu,setMenu]=useState(false); const [content,setContent]=useState<SiteContent>(defaultSiteContent);
  useEffect(()=>{const d=localStorage.getItem("tomoc-theme")==="dark";setDark(d);document.documentElement.classList.toggle("dark",d)},[]);
  useEffect(()=>{let active=true;fetch("/api/site-content",{cache:"no-store"}).then(response=>response.ok?response.json():Promise.reject()).then(result=>{if(active&&result.content)setContent(result.content)}).catch(()=>{});return()=>{active=false}},[]);
  const theme=()=>setDark(v=>{document.documentElement.classList.toggle("dark",!v);localStorage.setItem("tomoc-theme",!v?"dark":"light");return !v});
  const openProduct=(p:Product)=>{trackItems("select_item",[analyticsItem(p)],{item_list_name:"Онцлох бүтээгдэхүүн"},{dedupeMs:250});trackItems("view_item",[analyticsItem(p)],{},{dedupeMs:250});setSelected(p);setModal("product")};
  const heroImage=content.heroImage||defaultSiteContent.heroImage;
  const mobileHeroImage=content.mobileHeroImage||heroImage;
  const aboutImage=content.aboutImage||defaultSiteContent.aboutImage;
  const featuredProduct=catalog.find(product=>product.isFeatured)||catalog[0];
  const categoryCount=new Set(catalog.map(product=>product.category)).size;
  useEffect(()=>{document.body.classList.toggle("no-scroll",!!modal||menu)},[modal,menu]);
  return <>
    <div className="bg-ink py-2.5 text-center text-xs font-semibold tracking-wide text-white">УЛААНБААТАРТ 100,000₮-ӨӨС ДЭЭШ ЗАХИАЛГАД ХҮРГЭЛТ ҮНЭГҮЙ</div>
    <header className="glass sticky top-0 z-40 border-b border-black/5 dark:border-white/10">
      <div className="container flex h-[76px] items-center justify-between gap-5">
        <button className="md:hidden" aria-label="Цэс нээх" onClick={()=>setMenu(true)}><Menu/></button>
        <Link href="#home" className="text-[20px] font-black tracking-[-.05em]">TOMOC<span className="text-gold">.</span></Link>
        <nav className="desktop-only flex gap-7 text-sm font-semibold">{[["Нүүр","home"],["Бүтээгдэхүүн","products"],["Бидний тухай","about"],["Асуулт","faq"],["Холбоо барих","contact"]].map(x=><a key={x[1]} href={`#${x[1]}`} className="transition hover:text-gold">{x[0]}</a>)}</nav>
        <div className="flex items-center gap-1">
          <IconButton label="Хайх" onClick={()=>setModal("search")}><Search size={20}/></IconButton>
          <IconButton label="Өнгө солих" onClick={theme}>{dark?<Sun size={20}/>:<Moon size={20}/>}</IconButton>
          <IconButton label="Бүртгэл" onClick={()=>setModal("account")} extra="desktop-only"><CircleUserRound size={20}/></IconButton>
          <WishlistLink/>
          <IconButton label="Сагс" onClick={()=>setModal("cart")}><ShoppingBag size={20}/>{cartCount>0&&<b className="absolute right-0 top-0 grid h-5 min-w-5 place-items-center rounded-full bg-gold px-1 text-[10px] text-white">{cartCount}</b>}</IconButton>
        </div>
      </div>
    </header>
    <main>
      <section id="home" className="container py-5 md:py-8">
        <div className="relative min-h-[720px] overflow-hidden rounded-[32px] bg-cloud shadow-soft md:min-h-[650px] dark:bg-neutral-900">
          <Image src={heroImage} alt="TOMOC Store гоо сайхан болон спорт хувцасны premium цуглуулга" fill priority sizes="(max-width:768px) 100vw, 1200px" className="hidden object-cover object-[62%_center] md:block md:object-center"/>
          <Image src={mobileHeroImage} alt="TOMOC Store гоо сайхан болон спорт хувцасны premium цуглуулга" fill priority sizes="100vw" className="object-cover object-[62%_center] md:hidden"/>
          <div className="absolute inset-0 bg-gradient-to-t from-black/65 via-black/5 to-transparent md:bg-gradient-to-r md:from-white md:via-white/60 md:to-transparent dark:md:from-black dark:md:via-black/30"/>
          <motion.div initial={{opacity:0,y:30}} animate={{opacity:1,y:0}} transition={{duration:.75}} className="absolute inset-x-5 bottom-8 max-w-[600px] text-white md:bottom-auto md:left-16 md:right-auto md:top-1/2 md:-translate-y-1/2 md:text-ink dark:md:text-white">
            <div className="mb-6 inline-flex items-center gap-2 rounded-full bg-white/90 px-4 py-2 text-xs font-bold leading-none text-ink shadow"><Sparkles size={14} className="text-gold"/> {content.heroEyebrow}</div>
            <h1 className="display-serif block text-[48px] font-medium leading-[.94] tracking-[-.055em] md:text-[78px]">{content.heroTitle}</h1>
            <p className="mt-6 text-sm font-medium md:text-base">{content.heroSubtitle}</p>
            <div className="mt-8 flex flex-wrap gap-3"><a href="#products" className="btn btn-black"><ShoppingBag size={18}/> {content.primaryCtaText}</a><a href={content.messengerUrl||messenger} target="_blank" className="btn bg-white text-ink"><MessageCircle size={18}/> {content.messengerText||"Messenger"}</a><a href={whatsapp} target="_blank" className="btn bg-[#25D366] text-white"><MessageCircle size={18}/> WhatsApp</a></div>
          </motion.div>
          <div className="absolute right-6 top-6 hidden max-w-xs rounded-2xl bg-white/90 p-4 text-ink shadow backdrop-blur md:block"><div className="flex items-center gap-2 text-sm font-bold"><Truck size={17} className="text-gold"/> Хүргэлт</div><p className="mt-1 text-xs text-neutral-500">{content.deliveryText}</p></div>
        </div>
      </section>

      <Products catalog={catalog} setCatalog={setCatalog} openProduct={openProduct}/>

      <section id="about" className="section bg-cloud dark:bg-neutral-900"><div className="container grid items-center gap-10 md:grid-cols-2 md:gap-16">
        <motion.div {...fade} className="relative min-h-[480px] overflow-hidden rounded-4xl"><Image src={aboutImage} fill sizes="(max-width:768px) 100vw, 50vw" alt="TOMOC Store-ийн сонгосон гоо сайхны бүтээгдэхүүн" className="object-cover"/><div className="absolute bottom-5 left-5 rounded-2xl bg-white p-4 text-ink shadow"><b className="block text-2xl">100%</b><span className="text-xs text-neutral-500">чанарт анхаарсан сонголт</span></div></motion.div>
        <motion.div {...fade}><span className="eyebrow">TOMOC-ийн түүх</span><h2 className="title">{content.aboutTitle}</h2><p className="subtitle">{content.aboutBody}</p><div className="mt-8 grid grid-cols-3 gap-4"><Stat n={catalog.length?String(catalog.length):"—"} t="бүтээгдэхүүн"/><Stat n={categoryCount?String(categoryCount):"—"} t="ангилал"/><Stat n="24–48" t="цагийн хүргэлт"/></div></motion.div>
      </div></section>

      <FAQ content={content}/>

      <section id="contact" className="section bg-cloud dark:bg-neutral-900"><div className="container text-center"><motion.div {...fade}><span className="eyebrow">Танд тусалъя</span><h2 className="title">Захиалгаа шууд өгөөрэй.</h2><p className="subtitle mx-auto max-w-xl">Бүтээгдэхүүн сонгох, размер тааруулах, захиалгаа хянах — бид утас болон WhatsApp-аар хурдан хариулна.</p><div className="mx-auto mt-9 grid max-w-2xl gap-3 sm:grid-cols-2"><a className="group rounded-3xl bg-ink p-6 text-left text-white shadow-soft transition hover:-translate-y-1" href={`tel:${storeConfig.contact.orderPhone}`}><span className="text-xs font-bold uppercase tracking-[.16em] text-white/55">Захиалгын үндсэн утас</span><span className="mt-3 flex items-center justify-between text-3xl font-bold tracking-tight">{storeConfig.contact.orderPhone}<ArrowRight className="transition group-hover:translate-x-1"/></span><span className="mt-2 block text-sm text-white/60">Дарж шууд залгах</span></a><a className="group rounded-3xl bg-[#25D366] p-6 text-left text-white shadow-soft transition hover:-translate-y-1" href={whatsapp} target="_blank" rel="noreferrer"><span className="text-xs font-bold uppercase tracking-[.16em] text-white/70">WhatsApp захиалга</span><span className="mt-3 flex items-center justify-between text-3xl font-bold tracking-tight">{storeConfig.contact.whatsappDisplay}<MessageCircle className="transition group-hover:scale-110"/></span><span className="mt-2 block text-sm text-white/75">Дарж чат эхлүүлэх</span></a></div><div className="mt-5 flex flex-wrap justify-center gap-3"><a className="btn btn-soft" href={messenger} target="_blank"><MessageCircle size={18}/> Messenger</a><a className="btn btn-soft" href={facebook} target="_blank"><Facebook size={18}/> Facebook</a></div><button onClick={()=>setModal("track")} className="mt-8 text-sm font-bold underline underline-offset-4"><PackageCheck size={18} className="mr-2 inline"/>Захиалга хянах</button></motion.div></div></section>
    </main>
    <Footer content={content}/>
    <div className="fixed bottom-24 right-4 z-30 flex flex-col gap-3 md:bottom-5"><a href={messenger} target="_blank" aria-label="Messenger" className="grid h-12 w-12 place-items-center rounded-full bg-[#1877F2] text-white shadow-lg"><MessageCircle/></a><a href={whatsapp} target="_blank" aria-label="WhatsApp" className="grid h-12 w-12 place-items-center rounded-full bg-[#25D366] text-white shadow-lg"><MessageCircle/></a></div>
    <Chat/>
    {featuredProduct&&<MobileBuyBar product={featuredProduct} onBuy={()=>{add(featuredProduct);setModal("cart")}}/>}
    <AnimatePresence>{menu&&<MobileMenu close={()=>setMenu(false)} account={()=>{setMenu(false);setModal("account")}}/>}</AnimatePresence>
    <AnimatePresence>{modal&&<ModalView type={modal} close={()=>setModal(null)} product={selected} catalog={catalog} setModal={setModal}/>}</AnimatePresence>
  </>;
}

function IconButton({children,label,onClick,extra=""}:{children:React.ReactNode,label:string,onClick:()=>void,extra?:string}){return <button aria-label={label} onClick={onClick} className={`relative grid h-11 w-11 place-items-center rounded-full transition hover:bg-cloud dark:hover:bg-neutral-800 ${extra}`}>{children}</button>}

function Products({catalog,setCatalog,openProduct}:{catalog:Product[],setCatalog:(products:Product[])=>void,openProduct:(p:Product)=>void}){
  const [cat,setCat]=useState("Бүгд");const [query,setQuery]=useState("");const [loading,setLoading]=useState(true);const [loadError,setLoadError]=useState(false);
  const listTracked=useRef(false);
  useEffect(()=>{let active=true;fetch("/api/products",{cache:"no-store"}).then(response=>response.ok?response.json():Promise.reject()).then(result=>{if(active&&Array.isArray(result.products))setCatalog(result.products)}).catch(()=>{if(active)setLoadError(true)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[setCatalog]);
  useEffect(()=>{const track=()=>{if(!loading&&!listTracked.current&&window.tomocAnalyticsConsent){listTracked.current=true;trackItems("view_item_list",catalog.slice(0,12).map(product=>analyticsItem(product)),{item_list_name:"Онцлох бүтээгдэхүүн"},{dedupeKey:"view_item_list:featured",oncePerSession:true})}};track();window.addEventListener("tomoc:analytics-ready",track);return()=>window.removeEventListener("tomoc:analytics-ready",track)},[loading,catalog]);
  const cats=["Бүгд",...Array.from(new Set(catalog.map(item=>item.category)))];const filtered=catalog.filter(product=>(cat==="Бүгд"||product.category===cat)&&product.name.toLowerCase().includes(query.toLowerCase()));
  return <section id="products" className="section"><div className="container"><motion.div {...fade} className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><span className="eyebrow">Танд зориулсан</span><h2 className="title">Онцлох бүтээгдэхүүн</h2><p className="subtitle">Өдөр бүр илүү сайхныг мэдрүүлэх нямбай сонголт.</p></div><div className="relative"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-neutral-400" size={18}/><input aria-label="Бүтээгдэхүүн хайх" className="input pl-11 md:w-72" placeholder="Бүтээгдэхүүн хайх..." value={query} onChange={event=>setQuery(event.target.value)}/></div></motion.div>{loadError&&<p className="mt-5 rounded-xl bg-amber-50 p-3 text-sm text-amber-800">Live catalog ачаалсангүй. Түр хадгалсан бүтээгдэхүүнийг харуулж байна.</p>}<div className="hide-scroll mt-8 flex gap-2 overflow-auto pb-2">{cats.map(category=><button key={category} onClick={()=>setCat(category)} className={`whitespace-nowrap rounded-full px-5 py-2.5 text-sm font-bold transition ${cat===category?"bg-ink text-white dark:bg-white dark:text-ink":"bg-cloud dark:bg-neutral-800"}`}>{category}</button>)}</div>{loading?<div className="mt-7 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{[0,1,2].map(item=><div key={item} className="aspect-[4/4.6] animate-pulse rounded-[26px] bg-cloud dark:bg-neutral-800"/>)}</div>:<motion.div layout className="mt-7 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{filtered.map((product,index)=><ProductCard key={product.id} p={product} open={()=>openProduct(product)} i={index}/>)}</motion.div>}{!loading&&!filtered.length&&<div className="py-20 text-center text-neutral-500">Таны хайлтад тохирох бүтээгдэхүүн олдсонгүй.</div>}</div></section>
}

function cardSummary(product:Product){const text=(product.benefit||product.description||"").split(",").slice(0,3).join(", ").trim();return text.length>120?`${text.slice(0,117)}...`:text}
function ProductCard({p,open,i}:{p:Product,open:()=>void,i:number}){const {add,toggleWish,wishlist}=useStore();const stockText=typeof p.stock==="number"?(p.stock>0?"Бэлэн бараа":"Дууссан"):"Бэлэн бараа";return <motion.article layout initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.05}} className="group"><div className="relative aspect-[4/4.6] overflow-hidden rounded-[26px] bg-cloud"><Image src={p.image} alt={p.name} fill sizes="(max-width:640px) 100vw, (max-width:1024px) 50vw, 33vw" className="object-cover transition duration-700 group-hover:scale-[1.04]" onClick={open}/>{p.badge&&<span className="absolute left-4 top-4 rounded-full bg-white px-3 py-1.5 text-[11px] font-bold text-ink shadow">{p.badge}</span>}<button aria-label="Хадгалах" onClick={()=>toggleWish(p.id)} className="absolute right-4 top-4 grid h-10 w-10 place-items-center rounded-full bg-white text-ink shadow"><Heart size={18} fill={wishlist.includes(p.id)?"currentColor":"none"}/></button></div><div className="px-1 pt-5 text-left"><div className="mb-2 flex items-center justify-between"><span className="text-xs font-semibold text-neutral-500">{p.category}</span>{p.rating&&p.reviews?<span className="flex items-center gap-1 text-xs"><Star size={13} fill="#b79762" className="text-gold"/> {p.rating} ({p.reviews})</span>:<span className="text-xs text-neutral-400">{stockText}</span>}</div><button onClick={open} className="text-left"><h3 className="text-lg font-bold tracking-tight">{p.name}</h3></button><p className="mt-2 line-clamp-2 min-h-10 text-sm leading-5 text-neutral-500">{cardSummary(p)}</p><div className="mt-3 flex gap-2 font-bold"><span>{money(p.price)}</span>{p.oldPrice&&<del className="font-normal text-neutral-400">{money(p.oldPrice)}</del>}</div><div className="mt-4 grid grid-cols-2 gap-2"><button onClick={()=>add(p)} className="btn btn-black h-11 px-3 text-xs"><ShoppingBag size={15}/> Сагсанд нэмэх</button><button onClick={open} className="btn bg-cloud h-11 px-3 text-xs dark:bg-neutral-800">Дэлгэрэнгүй</button></div></div></motion.article>}

function Reviews(){return <section id="reviews" className="section"><div className="container"><motion.div {...fade} className="card px-6 py-14 text-center md:py-20"><span className="eyebrow">Бодит сэтгэгдэл</span><h2 className="title">Хэрэглэгчийн сэтгэгдэл удахгүй.</h2><p className="subtitle mx-auto max-w-xl">Баталгаажсан худалдан авалтын бодит сэтгэгдлийг энд нийтэлнэ.</p></motion.div></div></section>}

function FAQ({content}:{content:SiteContent}){const qs=content.faqItems.map(item=>[item.question,item.answer] as const);return <section id="faq" className="section"><div className="container grid gap-10 md:grid-cols-[.7fr_1.3fr]"><motion.div {...fade}><span className="eyebrow">Түгээмэл асуулт</span><h2 className="title">Мэдэх хэрэгтэй бүх зүйл.</h2><p className="subtitle">Өөр асуулт байна уу? Messenger-ээр бидэнтэй шууд холбогдоорой.</p></motion.div><div>{qs.map((q,i)=><FaqItem key={q[0]} q={q[0]} a={q[1]} first={i===0}/>)}</div></div></section>}
function FaqItem({q,a,first}:{q:string,a:string,first:boolean}){const [open,setOpen]=useState(first);return <div className="border-b border-black/10 py-5 dark:border-white/10"><button onClick={()=>setOpen(!open)} className="flex w-full items-center justify-between gap-4 text-left text-lg font-bold">{q}<ChevronDown className={`shrink-0 transition ${open?"rotate-180":""}`}/></button><AnimatePresence>{open&&<motion.p initial={{height:0,opacity:0}} animate={{height:"auto",opacity:1}} exit={{height:0,opacity:0}} className="overflow-hidden pr-10 pt-3 leading-7 text-neutral-500">{a}</motion.p>}</AnimatePresence></div>}

function Blog(){const posts=[{t:"Үсний төрлөө зөв таних 5 энгийн арга",c:"Үс арчилгаа",i:"/images/tomoc-beauty-campaign.png"},{t:"Seamless хувцсыг өдөр тутам хэрхэн хослуулах вэ?",c:"Загвар",i:"/images/tomoc-hero.png"},{t:"Өөртөө зориулсан 10 минутын morning reset",c:"Амьдралын хэв маяг",i:"/images/tomoc-beauty-campaign.png"}];return <section className="section bg-cloud dark:bg-neutral-900"><div className="container"><motion.div {...fade} className="flex items-end justify-between"><div><span className="eyebrow">TOMOC JOURNAL</span><h2 className="title">Танд хэрэгтэй тэмдэглэл</h2></div><button className="desktop-only text-sm font-bold">Бүгдийг унших <ArrowRight className="inline" size={16}/></button></motion.div><div className="mt-10 grid gap-6 md:grid-cols-3">{posts.map((post,index)=><motion.article key={`journal-${index}`} initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true,margin:"-80px"}} transition={{duration:.55,delay:index*.06}} className="group"><div className="relative aspect-[16/11] overflow-hidden rounded-3xl"><Image src={post.i} alt={post.t} fill sizes="(max-width:768px) 100vw, 33vw" className="object-cover transition duration-700 group-hover:scale-105"/></div><span className="mt-5 block text-xs font-bold uppercase tracking-wider text-gold">{post.c}</span><h3 className="mt-2 text-xl font-bold leading-tight">{post.t}</h3><button className="mt-4 text-sm font-bold">Унших <ArrowRight className="inline" size={15}/></button></motion.article>)}</div></div></section>}

function Newsletter(){const [done,setDone]=useState(false);return done?<div className="flex items-center gap-3 rounded-full bg-white/10 px-6 py-4 font-bold"><Check/> Баярлалаа! Бүртгэл амжилттай.</div>:<form onSubmit={e=>{e.preventDefault();setDone(true)}} className="flex w-full gap-2 md:w-[430px]"><input required type="email" aria-label="И-мэйл" placeholder="И-мэйл хаяг" className="h-13 min-w-0 flex-1 rounded-full border border-white/20 bg-white/10 px-5 text-white outline-none placeholder:text-white/40"/><button className="btn bg-white text-ink">Бүртгүүлэх</button></form>}

function Footer({content}:{content:SiteContent}){return <footer className="bg-ink py-14 text-white"><div className="container"><div className="grid gap-10 md:grid-cols-4"><div><b className="text-2xl tracking-tighter">TOMOC<span className="text-gold">.</span></b><p className="mt-4 max-w-xs text-sm leading-6 text-white/50">{content.footerDescription}</p><div className="mt-5 flex gap-3"><Instagram size={19}/><Facebook size={19}/></div></div><Foot title="Дэлгүүр" links={["Бүтээгдэхүүн","Шинэ бараа","Онцлох","Хямдрал"]}/><Foot title="Тусламж" links={["Хүргэлт","Буцаалт","Түгээмэл асуулт","Захиалга хянах"]}/><div><b>Холбоо барих</b><p className="mt-4 text-sm leading-7 text-white/50">Улаанбаатар, Монгол<br/>Захиалга: <a className="text-white" href={`tel:${content.contactPhone||storeConfig.contact.orderPhone}`}>{content.contactPhone||storeConfig.contact.orderPhone}</a><br/>WhatsApp: <a className="text-white" href={whatsapp}>{content.whatsappNumber||storeConfig.contact.whatsappDisplay}</a></p></div></div><div className="mt-12 flex flex-col justify-between gap-3 border-t border-white/10 pt-6 text-xs text-white/40 md:flex-row"><span>© {new Date().getFullYear()} TOMOC Store. Бүх эрх хуулиар хамгаалагдсан.</span><span className="flex flex-wrap items-center gap-2"><span>Нууцлал</span><span aria-hidden="true">•</span><span>Үйлчилгээний нөхцөл</span><span aria-hidden="true">•</span><button type="button" onClick={()=>window.dispatchEvent(new Event("tomoc:open-consent"))} className="rounded-full border border-white/15 px-3 py-1 font-bold text-white/70 underline-offset-4 transition hover:border-white/35 hover:text-white focus:outline-none focus:ring-2 focus:ring-white/50">Cookie тохиргоо</button></span></div></div></footer>}
function Foot({title,links}:{title:string,links:string[]}){return <div><b>{title}</b><div className="mt-4 flex flex-col gap-3 text-sm text-white/50">{links.map(x=><a href="#products" key={x}>{x}</a>)}</div></div>}
function Stat({n,t}:{n:string,t:string}){return <div><b className="block text-2xl md:text-3xl">{n}</b><span className="text-xs text-neutral-500">{t}</span></div>}

function MobileMenu({close,account}:{close:()=>void,account:()=>void}){return <motion.div initial={{x:"-100%"}} animate={{x:0}} exit={{x:"-100%"}} className="fixed inset-0 z-50 bg-[var(--bg)] p-6"><div className="flex items-center justify-between"><b className="text-xl">TOMOC.</b><IconButton label="Хаах" onClick={close}><X/></IconButton></div><nav className="mt-12 flex flex-col gap-7 text-3xl font-semibold">{[["Нүүр","home"],["Бүтээгдэхүүн","products"],["Бидний тухай","about"],["Асуулт","faq"],["Холбоо барих","contact"]].map(x=><a key={x[1]} href={`/#${x[1]}`} onClick={close}>{x[0]}</a>)}<Link href="/wishlist" onClick={close}>Хадгалсан бүтээгдэхүүн</Link></nav><button onClick={account} className="btn btn-black mt-10 w-full"><CircleUserRound/> Нэвтрэх / Бүртгүүлэх</button></motion.div>}

function ModalView({type,close,product,catalog,setModal}:{type:Modal,close:()=>void,product:Product|null,catalog:Product[],setModal:(m:Modal)=>void}){return <><motion.button aria-label="Хаах" onClick={close} className="fixed inset-0 z-50 bg-black/45 backdrop-blur-sm" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}/><motion.aside initial={{x:"100%"}} animate={{x:0}} exit={{x:"100%"}} transition={{type:"spring",damping:30,stiffness:260}} className="fixed bottom-0 right-0 top-0 z-50 w-full max-w-[540px] overflow-y-auto bg-[var(--bg)] p-6 shadow-2xl md:p-8"><div className="mb-7 flex items-center justify-between"><h2 className="text-2xl font-bold">{{cart:"Таны сагс",account:"Миний бүртгэл",track:"Захиалга хянах",checkout:"Захиалга баталгаажуулах",search:"Хайлт",product:"Бүтээгдэхүүн"}[type!]}</h2><IconButton label="Хаах" onClick={close}><X/></IconButton></div>{type==="cart"&&<Cart setModal={setModal}/>} {type==="checkout"&&<CheckoutForm compact/>} {type==="account"&&<CustomerAccount/>} {type==="track"&&<Track/>} {type==="search"&&<SearchPanel close={close} catalog={catalog}/>} {type==="product"&&product&&<ProductDetail p={product} catalog={catalog} setModal={setModal}/>}</motion.aside></>}

function Cart({setModal}:{setModal:(m:Modal)=>void}){const {cart,remove,setQty}=useStore();const sum=cart.reduce((s,x)=>s+x.price*x.qty,0);if(!cart.length)return <Empty icon={<ShoppingBag size={42}/>} title="Сагс одоогоор хоосон" text="Танд таалагдах бүтээгдэхүүнээ олж сагсандаа нэмээрэй."/>;return <div>{cart.map(x=><div key={x.id} className="flex gap-4 border-b border-black/10 py-4 dark:border-white/10"><div className="relative h-24 w-20 shrink-0 overflow-hidden rounded-xl"><Image src={x.image} alt={x.name} fill sizes="80px" className="object-cover"/></div><div className="min-w-0 flex-1"><b className="text-sm">{x.name}</b><p className="mt-1 text-sm text-neutral-500">{money(x.price)}</p><div className="mt-3 flex items-center gap-3"><button onClick={()=>setQty(x.id,x.qty-1)}><Minus size={16}/></button><span className="text-sm font-bold">{x.qty}</span><button onClick={()=>setQty(x.id,x.qty+1)}><Plus size={16}/></button></div></div><button onClick={()=>remove(x.id)} aria-label="Устгах" className="self-start"><X size={18}/></button></div>)}<div className="mt-6 flex justify-between text-lg font-bold"><span>Нийт</span><span>{money(sum)}</span></div><p className="mt-2 text-xs text-neutral-500">Хүргэлтийн төлбөр checkout дээр тооцогдоно.</p><button onClick={()=>setModal("checkout")} className="btn btn-black mt-6 w-full">Захиалга үргэлжлүүлэх <ArrowRight size={18}/></button></div>}

function Track(){
  type TrackedOrder={orderNumber:string;createdAt:string;status:string;customerName:string;total:number;items:{product_name:string;quantity:number}[];history:{status:string;created_at:string}[]};
  const [orderNumber,setOrderNumber]=useState("");const [phone,setPhone]=useState("");const [order,setOrder]=useState<TrackedOrder|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState("");
  const search=async()=>{if(!orderNumber.trim()||!phone.trim())return;setLoading(true);setError("");setOrder(null);try{const response=await fetch("/api/orders/track",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({orderNumber,phone})});const result=await response.json();if(!response.ok)throw new Error(result.error||"Захиалга олдсонгүй.");setOrder(result.order)}catch(cause){setError(cause instanceof Error?cause.message:"Алдаа гарлаа.")}finally{setLoading(false)}};
  const labels:Record<string,string>={pending:"Хүлээгдэж байна",confirmed:"Баталгаажсан",packing:"Бэлтгэж байна",shipped:"Хүргэлтэд",delivered:"Хүргэгдсэн",cancelled:"Цуцлагдсан",refunded:"Буцаагдсан"};
  return <div><p className="subtitle">Захиалгын дугаар болон захиалга өгөхдөө ашигласан утсаа оруулна уу.</p><div className="mt-6 space-y-3"><input className="input" aria-label="Захиалгын дугаар" placeholder="Жишээ: TOM-12345678" value={orderNumber} onChange={event=>setOrderNumber(event.target.value.toUpperCase())}/><input className="input" aria-label="Захиалгын утас" placeholder="Утасны дугаар" inputMode="tel" value={phone} onChange={event=>setPhone(event.target.value)}/><button onClick={search} disabled={loading||!orderNumber.trim()||!phone.trim()} className="btn btn-black w-full disabled:opacity-40">{loading?"Шалгаж байна...":"Захиалга хайх"}</button></div>{error&&<div role="alert" className="mt-6 rounded-2xl bg-amber-50 p-5 text-center text-sm text-amber-800">{error}</div>}{order&&<div className="mt-8 card p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs text-neutral-500">Захиалгын дугаар</p><b className="text-lg">{order.orderNumber}</b></div><span className="rounded-full bg-amber-100 px-3 py-1.5 text-xs font-bold text-amber-800">{labels[order.status]||order.status}</span></div><div className="mt-6 space-y-3 border-t border-black/10 pt-5 text-sm dark:border-white/10"><div className="flex justify-between"><span className="text-neutral-500">Огноо</span><b>{new Intl.DateTimeFormat("mn-MN",{dateStyle:"medium",timeStyle:"short"}).format(new Date(order.createdAt))}</b></div><div className="flex justify-between"><span className="text-neutral-500">Захиалагч</span><b>{order.customerName}</b></div><div className="flex justify-between"><span className="text-neutral-500">Бараа</span><b>{order.items.reduce((sum,item)=>sum+item.quantity,0)} ширхэг</b></div><div className="flex justify-between text-base"><span>Нийт</span><b>{money(order.total)}</b></div></div><a href={`${whatsapp}?text=${encodeURIComponent(`Сайн байна уу! ${order.orderNumber} дугаартай захиалгын төлөв шалгана уу.`)}`} target="_blank" rel="noreferrer" className="btn mt-6 w-full bg-[#25D366] text-white"><MessageCircle size={18}/> WhatsApp-аар лавлах</a></div>}</div>
}

function SearchPanel({close,catalog}:{close:()=>void,catalog:Product[]}){const [q,setQ]=useState("");const results=catalog.filter(product=>product.name.toLowerCase().includes(q.toLowerCase()));useEffect(()=>{const term=q.trim();if(term.length<2)return;const timer=window.setTimeout(()=>trackEvent("search",{search_term:term,results_count:results.length},{dedupeKey:`search:${term.toLowerCase()}`,dedupeMs:3000}),600);return()=>window.clearTimeout(timer)},[q,results.length]);const select=(product:Product)=>{trackItems("select_item",[analyticsItem(product)],{item_list_name:"Хайлтын үр дүн",search_term:q},{dedupeMs:250});close()};return <div><div className="relative"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-neutral-400"/><input autoFocus className="input h-14 pl-12" aria-label="Бүтээгдэхүүн хайх" placeholder="Юу хайж байна?" value={q} onChange={event=>setQ(event.target.value)}/></div><div className="mt-6 space-y-3">{results.map(product=><a href="#products" onClick={()=>select(product)} key={product.id} className="flex items-center gap-4 rounded-2xl p-2 hover:bg-cloud dark:hover:bg-neutral-900"><div className="relative h-16 w-14 overflow-hidden rounded-xl"><Image src={product.image} alt={product.name} fill sizes="56px" className="object-cover"/></div><div><b className="text-sm">{product.name}</b><p className="text-xs text-neutral-500">{money(product.price)}</p></div></a>)}</div></div>}

function ProductDetail({p,catalog,setModal}:{p:Product,catalog:Product[],setModal:(m:Modal)=>void}){
  const {add,toggleWish,wishlist}=useStore();
  const [zoom,setZoom]=useState(false);
  const gallery=Array.from(new Set([...(p.images||[]),p.image].filter(Boolean)));
  const [activeImage,setActiveImage]=useState(gallery[0]||p.image);
  return <div>
    <button onClick={()=>setZoom(!zoom)} className={`relative aspect-square w-full overflow-hidden rounded-3xl bg-cloud ${zoom?"cursor-zoom-out":"cursor-zoom-in"}`}><Image src={activeImage} alt={p.name} fill sizes="540px" className={`object-cover transition duration-500 ${zoom?"scale-150":""}`}/><span className="absolute bottom-4 right-4 rounded-full bg-white px-3 py-2 text-xs font-bold text-ink">{zoom?"Багасгах":"Томруулж харах"}</span></button>
    {gallery.length>1&&<div className="hide-scroll mt-3 flex gap-2 overflow-x-auto pb-1">{gallery.slice(0,8).map((image,index)=><button key={`${image}-${index}`} onClick={()=>{setActiveImage(image);setZoom(false)}} className={`relative h-20 w-20 shrink-0 overflow-hidden rounded-2xl border ${activeImage===image?"border-ink":"border-black/10"}`}><Image src={image} alt={`${p.name} зураг ${index+1}`} fill sizes="80px" className="object-cover"/></button>)}</div>}
    <div className="mt-6 flex items-start justify-between gap-4"><div><span className="eyebrow">{p.category}</span><h2 className="mt-2 text-3xl font-bold tracking-tight">{p.name}</h2></div><button onClick={()=>toggleWish(p.id)} className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-cloud dark:bg-neutral-800"><Heart fill={wishlist.includes(p.id)?"currentColor":"none"}/></button></div>
    <div className="mt-3 inline-flex rounded-full bg-cloud px-3 py-1.5 text-xs font-bold dark:bg-neutral-800">Монголд бэлэн бараа</div>
    <p className="mt-5 leading-7 text-neutral-500">{p.description}</p><div className="mt-5 text-2xl font-bold">{money(p.price)}</div>
    <div className="mt-6 grid grid-cols-3 gap-2 text-center text-xs font-bold"><div className="card p-3"><Truck className="mx-auto mb-2" size={20}/>24–48 цаг</div><div className="card p-3"><ShieldCheck className="mx-auto mb-2" size={20}/>Баталгаатай</div><div className="card p-3"><Zap className="mx-auto mb-2" size={20}/>Бэлэн</div></div>
    <button onClick={()=>{add(p);setModal("cart")}} className="btn btn-black mt-7 w-full"><ShoppingBag/> Сагсанд нэмэх</button><a href={whatsapp} target="_blank" rel="noreferrer" className="btn mt-3 w-full bg-[#25D366] text-white"><MessageCircle size={17}/> Шууд захиалах</a><Link href={`/products/${p.id}`} className="btn btn-soft mt-3 w-full">Бүтээгдэхүүний бүтэн хуудас <ArrowRight size={17}/></Link>
    <h3 className="mt-9 font-bold">Танд бас таалагдаж магадгүй</h3><div className="mt-4 grid grid-cols-2 gap-3">{catalog.filter(x=>x.id!==p.id).slice(0,2).map(x=><div className="card p-2" key={x.id}><div className="relative aspect-square overflow-hidden rounded-xl"><Image src={x.image} alt={x.name} fill sizes="200px" className="object-cover"/></div><b className="mt-2 block px-1 text-xs">{x.name}</b></div>)}</div>
  </div>
}

function Empty({icon,title,text}:{icon:React.ReactNode,title:string,text:string}){return <div className="grid min-h-[420px] place-items-center text-center"><div><div className="mx-auto mb-5 grid h-20 w-20 place-items-center rounded-full bg-cloud dark:bg-neutral-800">{icon}</div><h3 className="text-xl font-bold">{title}</h3><p className="mx-auto mt-3 max-w-sm text-sm leading-6 text-neutral-500">{text}</p></div></div>}

function Chat(){
  type ChatMessage={role:"assistant"|"user";text:string};
  const [open,setOpen]=useState(false);
  const [messages,setMessages]=useState<ChatMessage[]>([{role:"assistant",text:"Сайн байна уу! Би TOMOC AI туслах. Бүтээгдэхүүний үнэ, размер, өнгө, үлдэгдэл, хүргэлт, төлбөрийн талаар асуугаарай."}]);
  const [quickReplies,setQuickReplies]=useState(["Бүтээгдэхүүн","Үнэ асуух","Размер асуух","Хүргэлт","Захиалга"]);
  const [context,setContext]=useState<ChatContext>({});
  const [q,setQ]=useState("");
  const [loading,setLoading]=useState(false);
  const scrollRef=useRef<HTMLDivElement|null>(null);
  useEffect(()=>{scrollRef.current?.scrollTo({top:scrollRef.current.scrollHeight,behavior:"smooth"})},[messages,loading]);
  const ask=async(text:string)=>{
    const question=text.trim();if(!question||loading)return;
    setMessages(current=>[...current,{role:"user",text:question}]);setQ("");setLoading(true);
    try{
      const response=await fetch("/api/assistant",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({message:question,context})});
      const result=await response.json();
      if(!response.ok)throw new Error(result.reply||"Туслах түр ажиллахгүй байна.");
      setContext(result.context||{});
      if(Array.isArray(result.quickReplies)&&result.quickReplies.length)setQuickReplies(result.quickReplies);
      setMessages(current=>[...current,{role:"assistant",text:String(result.reply||"Мэдээлэл олдсонгүй.")}]);
    }catch(cause){
      setMessages(current=>[...current,{role:"assistant",text:cause instanceof Error?cause.message:"Туслах түр ажиллахгүй байна. Түр хүлээгээд дахин асуугаарай."}]);
    }finally{setLoading(false)}
  };
  const send=(event:React.FormEvent)=>{event.preventDefault();void ask(q)};
  return <div className="fixed bottom-24 left-4 z-30 md:bottom-5"><AnimatePresence>{open&&<motion.div initial={{opacity:0,y:15,scale:.96}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:15,scale:.96}} className="mb-3 flex h-[500px] w-[calc(100vw-32px)] max-w-[380px] flex-col overflow-hidden rounded-3xl border border-black/10 bg-[var(--bg)] shadow-2xl dark:border-white/10"><div className="flex items-center justify-between bg-ink p-4 text-white"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-full bg-white/15"><Bot size={20}/></div><div><b className="text-sm">TOMOC AI туслах</b><p className="text-[10px] text-green-300">● Онлайн • live product data</p></div></div><button aria-label="AI туслах хаах" onClick={()=>setOpen(false)}><X size={18}/></button></div><div ref={scrollRef} className="flex-1 space-y-3 overflow-auto p-4">{messages.map((message,index)=><div key={`${message.role}-${index}`} className={`max-w-[88%] whitespace-pre-line rounded-2xl px-4 py-3 text-sm leading-5 ${message.role==="user"?"ml-auto bg-ink text-white":"bg-cloud dark:bg-neutral-800"}`}>{message.text}</div>)}{loading&&<div className="inline-flex items-center gap-2 rounded-2xl bg-cloud px-4 py-3 text-sm text-neutral-500 dark:bg-neutral-800"><LoaderCircle className="animate-spin" size={16}/> Шалгаж байна...</div>}</div><div className="hide-scroll flex gap-2 overflow-x-auto border-t border-black/10 px-3 py-2 dark:border-white/10">{quickReplies.map(reply=><button key={reply} type="button" onClick={()=>ask(context.activeProductName?`${context.activeProductName} ${reply}`:reply)} disabled={loading} className="whitespace-nowrap rounded-full bg-cloud px-3 py-1.5 text-xs font-bold disabled:opacity-40 dark:bg-neutral-800">{reply}</button>)}</div><form onSubmit={send} className="flex gap-2 border-t border-black/10 p-3 dark:border-white/10"><input className="input" value={q} onChange={event=>setQ(event.target.value)} placeholder="Жишээ: Анн Чэри хэд вэ?"/><button disabled={loading||!q.trim()} aria-label="Илгээх" className="grid h-12 w-12 shrink-0 place-items-center rounded-full bg-ink text-white disabled:opacity-40"><ArrowRight/></button></form></motion.div>}</AnimatePresence><button aria-label="AI туслах нээх" onClick={()=>setOpen(!open)} className="flex h-12 w-12 items-center justify-center rounded-full bg-ink font-bold text-white shadow-xl md:h-13 md:w-auto md:gap-2 md:px-5"><Bot size={20}/><span className="hidden text-sm md:inline">AI туслах</span></button></div>
}
